[platformio]
default_envs = esp32dev

[env]
framework = arduino
monitor_speed = 115200
build_flags =
  -D TELEMETRY_HZ=50
  -D CLI_MAX_TOKENS=16
  -D USE_REAL_SENSORS=1
  -D USE_REAL_MOTOR_OUTPUT=1
  -D USE_DSHOT=0
lib_deps =
  bblanchon/ArduinoJson@^7.0.4

[env:esp32dev]
platform = espressif32
board = esp32dev

[env:stm32]
platform = ststm32
board = nucleo_f446re

[env:rpipico]
platform = raspberrypi
board = pico

[env:teensy41]
platform = teensy
board = teensy41
